# Generated by Django 4.2.4 on 2023-08-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='s_year',
            field=models.IntegerField(),
        ),
    ]
