# Generated by Django 4.2.4 on 2023-08-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anc', '0002_alter_students_roll_no_alter_students_s_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='s_depart',
            new_name='s_dep',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='s_section',
            new_name='s_sec',
        ),
    ]
