# Generated by Django 4.2.4 on 2023-08-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anc', '0003_rename_s_depart_students_s_dep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
